feedback changes
AgoraIO-Community/app-builder-docs pull request #14
Opened 2022-09-26 04:44 UTC by SupriyaAdep

Feedback mentioned in tickets https://agora.clickup.com/t/8556478/APP-3890

2022-09-27 11:25 UTC, bhupendra1011 requested changes

2022-09-27 11:25 UTC, bhupendra1011 commented on docs/first-party-extension/api-reference/events-library.md
> +send : (eventName: string, payload: string, persistLevel: EventPersistLevel ,receiver?: ReceiverUid ) => void
please remove the code snippet and update the send method 
`### send:(eventName: string, payload: string, persistLevel:EventPersistLevel, receiver?: EventPersistLevel) => void`

2022-09-27 11:25 UTC, bhupendra1011 commented on docs/first-party-extension/api-reference/events-library.md
> +on: (eventName: string, listener: Function ) => void
same as above

2022-09-27 11:25 UTC, bhupendra1011 commented on docs/first-party-extension/api-reference/events-library.md
> +off: (eventName?: string, listener?: Function ) => void
same as above

2022-09-29 05:32 UTC, bhupendra1011 commented on docs/first-party-extension/api-reference/events-library.md
> +###send : (eventName: string, payload: string, persistLevel: EventPersistLevel ,receiver?: ReceiverUid ) => void
there needs be a space between ### and rest of text and we can move it line no 55. it appears as below in preview : https://conferencing.agora.io/24010d60-26cf-4483-8aba-e7131687930a

2022-09-29 05:51 UTC, Adictya commented on docs/first-party-extension/api-reference/events-library.md
> +###send : (eventName: string, payload: string, persistLevel: EventPersistLevel ,receiver?: ReceiverUid ) => void
Will fix after merge

2022-09-29 05:51 UTC, merged